---
name: release

on:
  push:
    branches:
      - main

env:
  TEMPLATE_REPOSITORY: T-Systems-MMS/terraform-template

jobs:
  call-readme:
    if: github.repository != '$TEMPLATE_REPOSITORY'
    uses: T-Systems-MMS/.github/.github/workflows/terraform_docs.yml@release
  call-release:
    if: github.repository != '$TEMPLATE_REPOSITORY'
    uses: T-Systems-MMS/.github/.github/workflows/release.yml@release
    with:
      files: README.md
